export const questions = [
  "Who do you think is the most knowledgeable about crypto?",
  "Who gives the most helpful crypto investing advice?",
  "Who is the most positive person in crypto Twitter?",
  "Who is the funniest crypto influencer?",
  "Who is the most creative crypto artist?",
  "Who is the most inspirational woman in crypto?",
  "Who is leading innovation in crypto?",
  "Who do you think will build the next big crypto platform?",
  "Who is the most respected developer in crypto?",
  "Who is the best crypto educator on Twitter?",
  "Who has the best stories about early days of crypto?",
  "Who promotes crypto adoption in a positive way?",
  "Who gives back the most to the crypto community?",
  "Who do you think will achieve great things in crypto?",
  "Who is the most transparent crypto influencer?",
  "Who has the most unique crypto takes?",
  "Who is the best at keeping positive in a crypto bear market?",
  "Who has the best crypto memes?",
  "Who has introduced you to the most promising crypto projects?",
  "Who promotes crypto while staying grounded?",
  "Who throws the best crypto Twitter spaces?",
  "Who gives the most NFT alpha?",
  "Who has the best crypto Haiku poems?",
  "Who do you look up to most in the crypto space?",
  "Who has the best crypto threads?",
  "Who makes complex crypto concepts easy to understand?",
  "Who gives the best Web3 product feedback?",
  "Who is your favorite person to talk crypto with?",
  "Who cheers you up when the crypto markets are down?",
  "Who do you trust most for crypto safety tips?",
  "Who is the most supportive crypto friend?",
  "Who is your go-to for crypto banter?",
  "Who would you want on your crypto trivia team?",
  "Who introduced you to your favorite crypto rabbit hole?",
  "Who is leading innovation in DeFi?",
  "Who has the most compelling vision for crypto's future?",
  "Who gives back the most to the crypto community?",
  "Who is your favorite person to collaborate on crypto projects with?",
  "Who gives the most inspirational crypto speeches?",
  "Who has the best collection of crypto punks?",
  "Who takes the most unique crypto photos?",
  "Who has the wittiest crypto quips?",
  "Who is the best at making newbies feel welcome in crypto?",
  "Who do you look up to as a role model in crypto?",
  "Who has the best crypto merch?",
  "Who promotes ethics in crypto most?",
  "Who is leading innovation in NFTs?",
  "Who gives the most thoughtful feedback on crypto ideas?",
  "Who would you want by your side if you launched a crypto startup?",
  "Who radiates positivity in the crypto space?",
];
